### ISSUE TITLE
Iteration Plan of v2.13.0 - May 2021

### ISSUE THREAD

**Issue by ZwwWayne** [open-mmlab/mmdetection#5064]
MMDetection v2.12.0 will be released at the end of April. 
We list our plan for v2.13.0, which will be released at the end of May.
The PRs from the communities will also be listed here.
Thus, developers could comprehensively know the plan and the progress.

Algorithms:

- [x] Seesaw Loss for long-tailed instance segmentation (https://github.com/open-mmlab/mmdetection/pull/5128)
- [ ] Panoptic FPN (#4969 and more)
- [ ] Mosaic Augmentation (#4937)
- [x] Centernet (#4602)

Features:
- [ ] Support onnx2tensorrt with multi-batch for the listed models (TBA)
- [ ] Add evaluattion tool for converted TensorRT models (TBA)
- [ ] Add dataset downloading and extraction scripts for convenience (#5041)
- [ ] Support PointRend model exporting to ONNX (#4977)
- [ ] NMS update to speed up exporting to ONNX (#4990)
- [x] Add `soft_mask_target` as a config option to allow non-binary masks for training (#4615)
- [x] Supports for exporting CornerNet to ONNX with dynamic shapes and comparable performance https://github.com/open-mmlab/mmdetection/pull/5112

Enhancements:
- [ ] Add `simple_test` to dense heads and unify the mixins for dense heads (#5061)

Fixes:
- [x] Discard bboxes with sizes equals to min_bbox_size (#5011)

If you have created a PR and wish it to be merged in this version, feel free to leave a message in this issue. We will update our plan accordingly here.

**Comment by yeliudev** [comment]
Hi, may I ask that are there any comments on #5011? I'm not sure whether there is a better solution, but this PR works in my case.

**Comment by ZwwWayne** [comment]
> Hi, may I ask that are there any comments on #5011? I'm not sure whether there is a better solution, but this PR works in my case.

Hi @yeliudev ,
Thanks for your PR. It's been added.

**Comment by hokmund** [comment]
Could you please add my PR that extends flexibility of YOLOv3 architecture to this release?
https://github.com/open-mmlab/mmdetection/pull/5218
