### ISSUE TITLE
Progress of Chinese Documentation

### ISSUE THREAD

**Issue by ZwwWayne** [open-mmlab/mmdetection#5529]
We are building Chinese Documentation now, PRs of translation from the community are welcomed.
To make the community fully aware of the progress, we list the progress here. Please feel free to leave a message and create a PR if you are willing to translate any one of the documentation.

- [x] docs_zh-CN/2_new_data_model.md #5618 
- [ ] docs_zh-CN/useful_tools.md 
- [x] docs_zh-CN/model_zoo.md  #5827 
- [x] docs_zh-CN/tutorials/onnx2tensorrt.md #7219 
- [ ] docs_zh-CN/tutorials/pytorch2onnx.md 
- [x] docs_zh-CN/conventions.md #5825 
- [x] docs_zh-CN/tutorials/data_pipeline.md #5662
- [x] docs_zh-CN/tutorials/customize_dataset.md #5915
- [ ] docs_zh-CN/tutorials/customize_models.md
- [x] docs_zh-CN/tutorials/customize_losses.md #5826 
- [ ] docs_zh-CN/tutorials/customize_runtime.md 
- [x] docs_zh-CN/tutorials/finetune.md #7188 
- [x] docs_zh-CN/tutorials/init_cfg.md #7178
- [x] docs_zh-CN/robustness_benchmarking.md #6375
- [x] docs_zh-CN/tutorials/config.md #5558
- [x] docs_zh-CN/get_started.md #5421
- [x] docs_zh-CN/1_exist_data_model.md #5423
- [x] docs_zh-CN/3_exist_data_new_model.md #5369 
- [x] docs_zh-CN/compatibility.md #5419
- [x] docs_zh-CN/projects.md #5530
- [x] docs_zh-CN/faq.md #5408

**Comment by noobying** [comment]
docs_zh-CN/2_new_data_model.md

**Comment by BIGWangYuDong** [comment]
@noobying Do you want to create a PR about the Chinese version of `docs_zh-CN/2_new_data_model.md` ?

**Comment by noobying** [comment]
I'm just starting to translate this  `docs_zh-CN/2_new_data_model.md`. Should I create a PR when I finish translation?

**Comment by RangiLyu** [comment]
> I'm just starting to translate this `docs_zh-CN/2_new_data_model.md`. Should I create a PR when I finish translation?
> @BIGWangYuDong

You can open a PR first and mark it as WIP or add [WIP] in the title.

**Comment by jliu-ac** [comment]
docs_zh-CN/tutorials/customize_models.md

**Comment by jliu-ac** [comment]
> > docs_zh-CN/tutorials/customize_models.md
> 
> Hi @jliu-ac , Thanks for your reply. Once the PR is created, we will arrange review A.S.A.P.

I have submitted a PR, looking forward the review and advice:)

**Comment by q3394101** [comment]
认领 docs_zh-CN/useful_tools.md
