### ISSUE TITLE
Iteration Plan of v2.19.0 - November 2021

### ISSUE THREAD

**Issue by RangiLyu** [open-mmlab/mmdetection#6421]
# Iteration Plan of v2.19.0 - November 2021

MMDetection v2.18.0 has been released [here](https://github.com/open-mmlab/mmdetection/releases/tag/v2.18.0).
We list our plan for v2.19.0, which will be released on November 27th.
The PRs from the communities will also be listed here.
Thus, developers could comprehensively know the plan and the progress.

### Algorithms:

- [x] Release YOLOX pretrained models #6443
- [x] Release QueryInst pretrained models #6460
- [x] #6342

### Features:

- [ ] #5982
- [ ] #5693
- [x] #6344
- [x] #6435

### Fixes:

- [x] #6396
- [x] #6398
- [x] #6432
- [x] #6488
- [x] #6482
- [x] #6501
- [ ] #6490

### Enhancements:

- [x] #6457
- [ ] #6352
- [x] #6405
- [x] #6442
- [x] #6514

### Docs:

- [x] #6375
- [x] #6401
- [x] #6545

### Community help wanted:

- [ ] Dataset download scripts. (#4932)
- [ ] CrowdDet implementation. (https://github.com/Purkialo/CrowdDet)

If you have created a PR and wish it to be merged in this version, feel free to leave a message in this issue. We will update our plan accordingly here.
