### ISSUE TITLE
[Bug]  Is yolox possible to use GHM loss?

### ISSUE THREAD

**Issue by JH95-ai** [open-mmlab/mmdetection#9545]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection/issues) and [Discussions](https://github.com/open-mmlab/mmdetection/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [ ] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmdetection) or [latest version (3.x)](https://github.com/open-mmlab/mmdetection/tree/dev-3.x).

### Task

I have modified the scripts/configs, or I'm working on my own tasks/models/datasets.

### Branch

master branch https://github.com/open-mmlab/mmdetection

### Environment

sys.platform: linux
Python: 3.7.11 (default, Jul 27 2021, 14:32:16) [GCC 7.5.0]
CUDA available: True
CUDA_HOME: /usr/local/cuda
GCC: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
PyTorch: 1.10.1
PyTorch compiling details: PyTorch built with:
  - GCC 7.3

  - CUDA Runtime 11.3
  - CuDNN 8.2
  - Magma 2.5.2
TorchVision: 0.11.2
OpenCV: 4.5.5
MMCV: 1.4.5
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 11.3
MMDetection: 2.25.3+

### Reproduces the problem - code sample

    bbox_head=dict(
        type='YOLOXHead',
        num_classes=3,
        in_channels=96,
        feat_channels=96,
        use_depthwise=True,
        stacked_convs=1,
        loss_cls=dict(
            type='GHMC',
            bins=30,
            momentum=0.75,
            use_sigmoid=True,
            loss_weight=1.0),
        loss_bbox=dict(
            type='GHMR',
            mu=0.02,
            bins=10,
            momentum=0.7,
            loss_weight=5.0),
        loss_obj=dict(
            type='GHMC',
            bins=30,
            momentum=0.75,
            use_sigmoid=True,
            loss_weight=1.0),
        act_cfg=dict(type='ReLU6')),

### Reproduces the problem - command or script

python dist/train.sh config/yolox/some.py

### Reproduces the problem - error message

  File "/home/xujh/anaconda3/envs/mmcls/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
TypeError: forward() missing 1 required positional argument: 'label_weight'

### Additional information

label_weights，how should i get?

**Comment by RangiLyu** [comment]
YOLOX does not have label weights. You can try to modify the code like this:
```
loss_cls = self.loss_cls(
                flatten_cls_preds.view(-1, self.num_classes)[pos_masks],
                cls_targets,
                torch.ones_like(cls_targets)) / num_total_samples
```

**Comment by JH95-ai** [comment]
Thanks your reply
